
const s1 = {
  name : 'Proteins',
  count : 0,
  limit : 2,
  items : [ this.item1, this.item2, this.item3, this.item4, this.item5, this.item6, this.item7, this.item8, ],
  limit_reached : false,
  title : document.querySelector('#s1-title'),
  choose : document.querySelector('#s1-choose-amount'),
  // counter : document.querySelector('#s1c'),

  item1 : {
    __proto__: itemMethods,
    get section() { return s1; }, 
    name : 'Tilapia',
    count : 0,
    limit : null,
    selected : false,
    limit_reached : false,
    button : document.querySelector('#s1-1'),
    counter : document.querySelector('#s1-1c'),
  },

  item2 : {
    __proto__: itemMethods,
    get section() { return s1; },
    name : 'Chicken Breast',
    count : 0,
    limit : null,
    selected : false,
    limit_reached : false,
    button : document.querySelector('#s1-2'),
    counter : document.querySelector('#s1-2c'),
},

 item3 : {
  __proto__: itemMethods,
  get section() { return s1; }, 
  name : 'Pork Chop',
  count : 0,
  limit : null,
  selected : false,
  limit_reached : false,
  button : document.querySelector('#s1-3'),
  counter : document.querySelector('#s1-3c'),

},

 item4 : {
  __proto__: itemMethods,
  get section() { return s1; }, 
  name : 'Tempeh',
  count : 0,
  limit : null,
  selected : false,
  limit_reached : false,
  button : document.querySelector('#s1-4'),
  counter : document.querySelector('#s1-4c'),
},

 item5 : {
  __proto__: itemMethods,
  get section() { return s1; }, 
  name : 'Tuna',
  count : 0,
  limit : null,
  selected : false,
  limit_reached : false,
  button : document.querySelector('#s1-5'),
  counter : document.querySelector('#s1-5c'),
},

 item6 : {
  __proto__: itemMethods,
    get section() { return s1; }, 
  name : 'Protein Trail Mix',
  count : 0,
  limit : null,
  selected : false,
  limit_reached : false,
  button : document.querySelector('#s1-6'),
  counter : document.querySelector('#s1-6c'),
},

 item7 : {
  __proto__: itemMethods,
    get section() { return s1; }, 
  name : 'Firm Tofu',
  count : 0,
  limit : null,
  selected : false,
  limit_reached : false,
  button : document.querySelector('#s1-7'),
  counter : document.querySelector('#s1-7c'),
},

 item8 : {
  __proto__: itemMethods,
    get section() { return s1; }, 
  name : 'Tempeh Cauliflower Patty',
  nameBR : 'Tempeh Cauli-<br>flower Patty',
  count : 0,
  limit : null,
  selected : false,
  limit_reached : false,
  button : document.querySelector('#s1-8'),
  counter : document.querySelector('#s1-8c'),
},
};
